version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_api_service
    ports:
      - "8080:8080"
    networks:
      - backend


networks:
  backend:

volumes:
  postgres_data:
