name: API Service for Continuous integration

on:
  push:
    branches: [ "v0.1" ]
  pull_request:
    branches: [ "v0.1" ]

jobs:
  build:
    runs-on: ubuntu-20.04  
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'  

    - name: Run Tests
      run: go test -v ./...

    - name: Build Go Binary
      run: GOOS=linux go build -o Market-360-Backend main.go